# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sociopathor}
  s.version = "0.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Olivier El Mekki"]
  s.date = %q{2011-08-21}
  s.email = %q{oelmekki@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/user_sessions_controller.rb",
    "app/controllers/users_controller.rb",
    "app/helpers/application_helper.rb",
    "app/models/user.rb",
    "app/models/user_session.rb",
    "app/views/layouts/application.html.erb",
    "app/views/user_sessions/new.html.erb",
    "app/views/users/edit.html.erb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/rails/generators/sociopathor/install/install_generator.rb",
    "lib/rails/generators/sociopathor/templates/authlogic.yml",
    "lib/rails/generators/sociopathor/templates/authlogic_connect_config.rb",
    "lib/rails/generators/sociopathor/templates/create_access_tokens.rb",
    "lib/rails/generators/sociopathor/templates/create_sessions.rb",
    "lib/rails/generators/sociopathor/templates/create_users.rb",
    "lib/rails/generators/sociopathor/templates/local_user.rb",
    "lib/rails/generators/sociopathor/templates/local_user_session.rb",
    "lib/rails/generators/sociopathor/templates/local_user_sessions_controller.rb",
    "lib/rails/generators/sociopathor/templates/local_users_controller.rb",
    "lib/sociopathor.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Social features in a rails engine}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.9"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<authlogic>, [">= 0"])
      s.add_runtime_dependency(%q<authlogic-connect>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_runtime_dependency(%q<oauth2>, ["= 0.4.1"])
      s.add_runtime_dependency(%q<authlogic>, [">= 0"])
      s.add_runtime_dependency(%q<authlogic-connect>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.9"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<authlogic>, [">= 0"])
      s.add_dependency(%q<authlogic-connect>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<oauth2>, ["= 0.4.1"])
      s.add_dependency(%q<authlogic>, [">= 0"])
      s.add_dependency(%q<authlogic-connect>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.9"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<authlogic>, [">= 0"])
    s.add_dependency(%q<authlogic-connect>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<oauth2>, ["= 0.4.1"])
    s.add_dependency(%q<authlogic>, [">= 0"])
    s.add_dependency(%q<authlogic-connect>, [">= 0"])
  end
end

